### ISSUE TITLE
Use proper opkg build package utilities

### ISSUE THREAD

**Issue by oneechanhax** [oneechanhax/azazel-build#1]
@tpimh hey, im trying to make packages by hand and it isnt going so well...
i need symlinks to be preserved properly and everything to use /usr instead of thinking the install prefix is the build package directory...
i tried using proot and fakeroot but those cant distinguish between files in the real root and in the fake root...

Can you link me to where you found out how to make opkgs?

**Comment by tpimh** [comment]
I'm currently using a slightly modified version of [opkg-buildpackage](https://github.com/tpimh/nenuzhnix-build/blob/master/root/nenuzhnix-tools/opkg-buildpackage) script. Ideally it should be updated and extended, but it works for me now, so it's fine.

**Comment by tpimh** [comment]
I just rewrote some parts of my version of opkg-buildpackage (for now only on [docker branch](https://github.com/tpimh/nenuzhnix-build/blob/docker/root/nenuzhnix-tools/opkg-buildpackage)) and I consider it somewhat usable now.

**Comment by oneechanhax** [comment]
I have switched to Alpinelinux's "[Alpine Package Keeper](https://git.alpinelinux.org/apk-tools/)" in favor of signed packages, proper documentation, better build tools, automated ones as well, and just well around speed.

Thanks for helping, but opkg doesnt seem like a powerful enough package manager for day to day systems or even server ones. Its great for embedded but apk-tools is just much more suited for my needs.
